const data = [
  ['Advia Centaur XP', ['IgE',
    'Total',
    'Active-B122',
    'EPO1',
    'Ferritin',
    'Folate',
    'RBC Folate',
    'Vitamin B12',
    'Anti-CCP2',
    'Vitamin D Total',
    'BNP',
    'CKMB',
    'Galectin-31',
    'High-sensitivity troponin I (TNIH)1',
    'Myoglobin',
    'NT-proBNP1',
    'TnI-Ultra™',
    'C-Peptide',
    'Insulin',
    'Anti-HBe2',
    'Anti-HBs-2',
    'HAV IgM',
    'HAV Total',
    'HBc IgM',
    'HBc Total',
    'HBeAg2',
    'HBsAgII2',
    'HBsAg',
    'HBsAg Confirmatory',
    'HCV3',
    'HIV 1/O/2 Enhanced (EHIV)3',
    'HIV Combo2,3',
    'Cyclosporine',
    'Everolimus1',
    'Tacrolimus1',
    'LBP1',
    'IL-61',
    'Enhanced Liver Fibrosis (ELF™) Test2',
    'HA (ELF Marker)2',
    'PIIINP (ELF Marker)2',
    'TIMP (ELF Marker)2',
    'Cortisol',
    'Homocysteine',
    'AFP',
    'Anti-Müllerian Hormone1',
    'BR 27.29',
    'CA 125II',
    'CA 15-3',
    'Calcitonin1',
    'CA 19-9',
    'CEA',
    'Free βhCG1',
    'Free PSA2',
    'PAPP-A1',
    'PSA',
    'PSA, Complexed',
    'Serum HER-2/neu',
    'AFP',
    'DHEAS',
    'Enhanced Estradiol',
    'FSH',
    'hCG',
    'LH',
    'PlGF1',
    'Progesterone',
    'Prolactin',
    'sFLT-11',
    'SHBG',
    'Testosterone',
    'Procalcitonin2',
    'Syphilis',
    'Carbamazepine',
    'Digitoxin',
    'Digoxin',
    'Gentamicin',
    'Phenobarbital',
    'Phenytoin',
    'Theophylline',
    'Tobramycin',
    'Valproic Acid',
    'Vancomycin',
    'Anti-TG',
    'Anti-TPO',
    'Free T3',
    'Free T4',
    'Intact PTH',
    'T Uptake',
    'Tg1',
    'Total T3',
    'Total T4',
    'TSH3-Ultra',
    'TSH',
    'CMV IgG1',
    'CMV IgM1',
    'Herpes I1',
    'Herpes II1',
    'Rubella IgG',
    'Rubella IgM',
    'Toxoplasma IgG',
    'Toxoplasma IgM']],

  ['Architect i2000SR', ['Active-B12',
    'B12',
    'Ferritin',
    'Folate',
    'Homocysteine',
    'Intact PTH',
    'Vitamin D',
    'AFP',
    'CA 125',
    'CA 15-3',
    'CA 19-9 (CA 19-9 XR)',
    'CEA',
    'CYFRA 21-1',
    'Free PSA',
    'HE-4',
    'Pepsinogen I',
    'Pepsinogen II',
    'PIVKA-II',
    'ProGRP',
    'SCC',
    'Total PSA',
    'BNP',
    'CK-MB',
    'Galectin-3',
    'Myoglobin',
    'Troponin-I',
    'Troponin-I (High Sensitive)',
    'CMV IgG',
    'CMV IgG Avidity',
    'CMV IgM',
    'Rubella IgG',
    'Rubella IgM',
    'Toxo IgG',
    'Toxo IgG Avidity',
    'Toxo IgM',
    'C-Peptide',
    'Hemoglobin A1c (Monitoring)',
    'Insulin',
    'DHEA-S',
    'Estradiol',
    'FSH',
    'hCG (Total Beta-hCG)',
    'LH',
    'Progesterone',
    'Prolactin',
    'SHBG',
    'Testosterone',
    'Testosterone 2nd Generation',
    'Anti-HAV IgG',
    'Anti-HAV IgM',
    'Anti-HBc',
    'Anti-HBc IgM',
    'Anti-HBe',
    'Anti-HBs',
    'Anti-HCV',
    'HBeAg',
    'HBsAg (Qualitative Conf.)',
    'HBsAg (Qualitative)',
    'HBsAg (Quantitative)',
    'HCV Ag',
    'Anti-CCP',
    'PIVKA-II',
    'Active-B12',
    'B12',
    'C-Peptide',
    'Cortisol',
    'Ferritin',
    'Folate',
    'Hemoglobin A1c (Monitoring)',
    'Homocysteine',
    'Insulin',
    'Intact PTH',
    'Vitamin D',
    'Chagas',
    'EBV EBNA-1-IgG',
    'EBV VCA IgG',
    'EBV VCA IgM',
    'Syphilis TP',
    'Anti-CCP',
    'NGAL',
    'Anti-HTLV-I/HTLV-II',
    'HIV Ag/Ab Combo',
    'Carbamazepine',
    'Digoxin',
    'Gentamicin',
    'Methotrexate',
    'Phenobarbital',
    'Phenytoin',
    'Theophylline',
    'Valproic Acid',
    'Vancomycin',
    'Anti-Tg',
    'Anti-TPO',
    'Free T3',
    'Free T4',
    'T-Uptake',
    'Total T3',
    'Total T4',
    'TSH',
    'Cyclosporine',
    'Sirolimus',
    'Tacrolimus']],

  ['ACL Elite Pro', [ 'AT',
    'DS',
    'F1+2',
    'HC-II',
    'HEP',
    'HMWK',
    'K',
    'PAI',
    'PC',
    'PF3',
    'PhL',
    'PI',
    'PK',
    'PL',
    'PLG',
    'PS',
    'SK',
    'TAFI',
    'TF',
    'TFPI',
    'TM',
    't-PA',
    'UK',
    'vWf']],

  ['D-10', [ 'A0',
    'Glumean',
    'Hba1A',
    'Hba1AT',
    'Hba1B',
    'Hba1C',
    'HbF',
    'HbTotal',
    'La1/CHB-1',
    'La1/CHB-2',
    'P3',
    'Totarea',
    'Variant']],

  [ 'IMMULITE 2000', ['AlaTOP Allergy Screen',
    ' Allergen-Specific IgE 3gAllergy',
    'Allergen-Specific IgG1',
    'Allergen-Specific IgG41',
    'ECP1',
    'IgE',
    'Total',
    'EPO',
    'Ferritin',
    'Folate',
    'RBC Folate',
    'Vitamin B12',
    'Anti-CCP',
    'Osteocalcin',
    'PYRILINKS-D',
    'CKMB',
    'D-Dimer',
    'High-sensitivity CRP',
    'Myoglobin',
    'NT-proBNP',
    'Troponin I',
    'C-Peptide ',
    'Insulin',
    'Microalbumin',
    'Growth Hormone (hGH)',
    'IGF-I',
    'IGFBP-3',
    'Anti-HBs',
    'Anti-HBs Quantitative',
    'Anti-HBc IgM',
    'Anti-HBc Total',
    'HBsAg',
    'HBsAg Confirmatory',
    'IL-R',
    'IL-6',
    'LBP',
    'ACTH',
    'Cortisol',
    'Homocysteine',
    'Oncology',
    'AFP',
    'CA 125 (OM-MA)',
    'CA 15-3 (BR-MA)',
    'CA 19-9(GI-MA)',
    'Calcitonin',
    'CEA',
    'Free PSA',
    'PAP',
    'PSA',
    'ß2-Microglobulin',
    'Gastrin',
    'Nicotine Metabolites',
    'Androstenedione',
    'DHEAS',
    'Estradiol',
    'Free Beta HCG1',
    'FSH',
    'hCG',
    'LH',
    'PAPP-A',
    'Progesterone',
    'Prolactin',
    'SHBG',
    'Testosterone',
    'Unconjugated Estriol',
    'EBV-EBNA IgG',
    'EBV-VCA IgG',
    'EBV-VCA IgM',
    'H. pylori IgG',
    'Syphilis',
    'Carbamazepine',
    'Digitoxin',
    'Digoxin',
    'Phenobarbital',
    'Phenytoin',
    'Theophylline',
    'Valproic Acid',
    'Anti-TG',
    'Anti-TPO',
    'Free T3',
    'Free T4',
    'Intact PTH',
    'T Uptake',
    'TBG',
    'Thyroglobulin',
    'Total T3',
    'Total T4',
    'TSH',
    'TSH, 3rd Generation',
    'TSI',
    'CMV IgG',
    'CMV IgM',
    'Herpes I & II IgG',
    'Rubella IgG',
    'Rubella IgM',
    'Toxoplasma IgG',
    'Toxoplasma IgM',
    'Canine TLI',
    'Canine Total T4',
    'Canine TSH',
    'Canine Free T4']],
  ['Advia 2000', [ '6-Acetylmorphine(6-AM)',
    'Acetaminophen',
    'Amphetamines',
    'Barbiturates',
    'Barbiturates, Serum',
    'Benzodiazepines',
    'Benzodiazepines, Serum',
    'Cannabinoids (THC)',
    'Cocaine Metabolite',
    'Ecstasy',
    'Ethanol',
    'Methadone',
    'Methadone Metabolites',
    'Opiates',
    'Phencyclidine',
    'Propoxyphene',
    'Salicylate',
    'Validity Test',
    'Tricyclic Antidepressants',
    'Alanine Aminotransferase',
    'Alanine Aminotransferase (P5P)',
    'Albumin (BCG)',
    'Albumin (BCP)',
    'Alkaline Phosphatase (AMP)',
    'Alkaline Phosphatase (DEA)',
    'Ammonia',
    'Amylase',
    'Aspartate Aminotransferase',
    'Aspartate Aminotransferase (P5P)',
    'Bilirubin, Direct',
    'Bilirubin, Total',
    'Calcium (Arsenazo)',
    'Calcium (CPC)',
    'Carbon Dioxide, Enzymatic',
    'Chloride (ISE)',
    'Cholesterol',
    'Cholinesterase',
    'Creatine Kinase',
    'Creatinine',
    'Creatinine, Enzymatic',
    'Fructosamine',
    'Gamma-Glutamyltransferase (GGT)',
    'Glucose (Hexokinase)',
    'Glucose (Oxidase)',
    'HDL Cholesterol',
    'Iron',
    'Lactate',
    'Lactate Dehydrogenase (L-P)',
    'Lactate Dehydrogenase (P-L)',
    'LDL Cholesterol',
    'Lipase',
    'Magnesiumb',
    'Microalbumin',
    'Pancreatic Amylase',
    'Phosphorusb',
    'Potassium',
    'Sodium',
    'Total Iron Binding Capacity (TIBC)',
    'Total Proteinb',
    'Total Protein (CSF/Urine)',
    'Triglyceridesb',
    'Urea Nitrogen (BUN)b',
    'Uric Acidb',
    'α1-Acid Glycoprotein',
    'α1-Antitrypsin',
    'Antistreptolysin O',
    'Apolipoprotein A1',
    'Apolipoprotein B',
    'β-2 Microglobulin',
    'CardioPhase hsCRP',
    'Complement C3',
    'Complement C4',
    'CRP',
    'CRP, Wide Range',
    'Cystatin C',
    'Ferritin',
    'Haptoglobin',
    'Hemoglobin A1c',
    'Immunoglobulin A',
    'Immunoglobulin G',
    'Immunoglobulin M',
    'Lipoprotein(a)',
    'Myoglobin',
    'Prealbumin',
    'Rheumatoid Factor',
    'Transferrin',
    'Carbamazepine',
    'Digoxin',
    'Gabepentin',
    'Gentamicin',
    'Lamotrigine',
    'Levetiracetam',
    'Lithium',
    'Phenobarbital',
    'Phenytoin',
    'Theophylline',
    'Tobramycin',
    'Topiramate',
    'Valproic Acid',
    'Vancomycin',
    'Zonisamide',
    'Creatinine Specimend',
    'Nitrite Specimen',
    'Oxidant Specimen',
    'pH Specimend',
    'Specific Gravity Specimen' ]]]
